spring.application.name=NBCC-Resto

spring.datasource.url=jdbc:mysql://localhost:3306/popup_restaurant
spring.datasource.username=devJPA
spring.datasource.password=NBCC1234!

spring.jpa.hibernate.ddl-auto=update

server.port=8080

logging.level.nbcc=DEBUG
logging.level.org.springframework.web=DEBUG
logging.file.name=logs/web.log

auth.rest.api.url=http://localhost
auth.rest.api.port=8082

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=funmbiolajubu@gmail.com
spring.mail.password=ybfk entm jzyb qhwy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
veil.mail.from=funmbiolajubu@gmail.com