spring.application.name=NBCC-Resto

spring.datasource.url=jdbc:mysql://localhost:3306/popup_restaurant
spring.datasource.username=devJPA
spring.datasource.password=NBCC1234!

spring.jpa.hibernate.ddl-auto=update

server.port=8080

logging.level.root=INFO
logging.level.nbcc.games=DEBUG
logging.file.name=logs/web.log

auth.rest.api.url=http://localhost
auth.rest.api.port=8082