spring.application.name=NBCC-Resto

spring.datasource.url=jdbc:mysql://localhost:3306/popup_restaurant
spring.datasource.username=devJPA
spring.datasource.password=NBCC1234!

spring.jpa.hibernate.ddl-auto=update

server.port=8080

logging.level.nbcc=DEBUG
logging.level.org.springframework.web=DEBUG
logging.file.name=logs/web.log

sentry.dsn=https://568ceb0132412752a16e1283d25ed37a@o4511119889727488.ingest.us.sentry.io/4511119898836992
sentry.traces-sample-rate=1.0
sentry.send-default-pii=true

auth.rest.api.url=http://localhost
auth.rest.api.port=8082